# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI\Current_Position.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from Storage_Signal import signal
style_on = """ QLabel{background-color: #25BE75;
border-radius: 25px;}
"""
style_off = """ QLabel{background-color: rgb(240,240,240);
border-radius: 25px;}
"""
class Ui_Current_Position(object):
    def setupUi(self, Current_Position):
        self.B_Limit_Switch_Magnet = QtWidgets.QPushButton(Current_Position)
        self.B_Limit_Switch_Magnet.setGeometry(QtCore.QRect(1077, 530, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.B_Limit_Switch_Magnet.setFont(font)
        self.B_Limit_Switch_Magnet.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    \n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.B_Limit_Switch_Magnet.setObjectName("B_Limit_Switch_Magnet")
        self.F_Current_Position = QtWidgets.QFrame(Current_Position)
        self.F_Current_Position.setGeometry(QtCore.QRect(1057, 155, 331, 371))
        self.F_Current_Position.setStyleSheet("QFrame{\n"
"    border: 2px solid;\n"
"    border-radius: 20px;\n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.F_Current_Position.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.F_Current_Position.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F_Current_Position.setObjectName("F_Current_Position")
        self.L_CP_Theta1 = QtWidgets.QLabel(self.F_Current_Position)
        self.L_CP_Theta1.setGeometry(QtCore.QRect(40, 30, 100, 21))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.L_CP_Theta1.setFont(font)
        self.L_CP_Theta1.setStyleSheet("QLabel{\n"
"    border: none;\n"
"}")
        self.L_CP_Theta1.setAlignment(QtCore.Qt.AlignCenter)
        self.L_CP_Theta1.setObjectName("L_CP_Theta1")
        self.Line_CP = QtWidgets.QFrame(self.F_Current_Position)
        self.Line_CP.setGeometry(QtCore.QRect(180, 10, 3, 361))
        self.Line_CP.setLineWidth(1)
        self.Line_CP.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line_CP.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.Line_CP.setObjectName("Line_CP")
        self.I_CP_Theta1 = QtWidgets.QLabel(self.F_Current_Position)
        self.I_CP_Theta1.setGeometry(QtCore.QRect(40, 60, 100, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.I_CP_Theta1.setFont(font)
        self.I_CP_Theta1.setStyleSheet("QLabel{\n"
"    border-radius: 10px;\n"
"}")
        self.I_CP_Theta1.setAlignment(QtCore.Qt.AlignCenter)
        self.I_CP_Theta1.setObjectName("I_CP_Theta1")
        self.label_7 = QtWidgets.QLabel(self.F_Current_Position)
        self.label_7.setGeometry(QtCore.QRect(40, 115, 100, 21))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel{\n"
"    border: none;\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.I_CP_Theta2 = QtWidgets.QLabel(self.F_Current_Position)
        self.I_CP_Theta2.setGeometry(QtCore.QRect(40, 145, 100, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.I_CP_Theta2.setFont(font)
        self.I_CP_Theta2.setStyleSheet("QLabel{\n"
"    border-radius: 10px;\n"
"}")
        self.I_CP_Theta2.setAlignment(QtCore.Qt.AlignCenter)
        self.I_CP_Theta2.setObjectName("I_CP_Theta2")
        self.I_CP_Theta3 = QtWidgets.QLabel(self.F_Current_Position)
        self.I_CP_Theta3.setGeometry(QtCore.QRect(40, 230, 100, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.I_CP_Theta3.setFont(font)
        self.I_CP_Theta3.setStyleSheet("QLabel{\n"
"    border-radius: 10px;\n"
"}")
        self.I_CP_Theta3.setAlignment(QtCore.Qt.AlignCenter)
        self.I_CP_Theta3.setObjectName("I_CP_Theta3")
        self.L_CP_Theta3 = QtWidgets.QLabel(self.F_Current_Position)
        self.L_CP_Theta3.setGeometry(QtCore.QRect(40, 200, 100, 21))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.L_CP_Theta3.setFont(font)
        self.L_CP_Theta3.setStyleSheet("QLabel{\n"
"    border: none;\n"
"}")
        self.L_CP_Theta3.setAlignment(QtCore.Qt.AlignCenter)
        self.L_CP_Theta3.setObjectName("L_CP_Theta3")
        self.I_CP_Theta4 = QtWidgets.QLabel(self.F_Current_Position)
        self.I_CP_Theta4.setGeometry(QtCore.QRect(40, 320, 100, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.I_CP_Theta4.setFont(font)
        self.I_CP_Theta4.setStyleSheet("QLabel{\n"
"    border-radius: 10px;\n"
"}")
        self.I_CP_Theta4.setAlignment(QtCore.Qt.AlignCenter)
        self.I_CP_Theta4.setObjectName("I_CP_Theta4")
        self.L_CP_Theta4 = QtWidgets.QLabel(self.F_Current_Position)
        self.L_CP_Theta4.setGeometry(QtCore.QRect(40, 290, 100, 21))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.L_CP_Theta4.setFont(font)
        self.L_CP_Theta4.setStyleSheet("QLabel{\n"
"    border: none;\n"
"}")
        self.L_CP_Theta4.setAlignment(QtCore.Qt.AlignCenter)
        self.L_CP_Theta4.setObjectName("L_CP_Theta4")
        self.I_CP_Py = QtWidgets.QLabel(self.F_Current_Position)
        self.I_CP_Py.setGeometry(QtCore.QRect(210, 190, 100, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.I_CP_Py.setFont(font)
        self.I_CP_Py.setStyleSheet("QLabel{\n"
"    border-radius: 10px;\n"
"}")
        self.I_CP_Py.setAlignment(QtCore.Qt.AlignCenter)
        self.I_CP_Py.setObjectName("I_CP_Py")
        self.I_CP_Pz = QtWidgets.QLabel(self.F_Current_Position)
        self.I_CP_Pz.setGeometry(QtCore.QRect(210, 300, 100, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.I_CP_Pz.setFont(font)
        self.I_CP_Pz.setStyleSheet("QLabel{\n"
"    border-radius: 10px;\n"
"}")
        self.I_CP_Pz.setAlignment(QtCore.Qt.AlignCenter)
        self.I_CP_Pz.setObjectName("I_CP_Pz")
        self.L_CP_Py = QtWidgets.QLabel(self.F_Current_Position)
        self.L_CP_Py.setGeometry(QtCore.QRect(210, 160, 100, 21))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.L_CP_Py.setFont(font)
        self.L_CP_Py.setStyleSheet("QLabel{\n"
"    border: none;\n"
"}")
        self.L_CP_Py.setAlignment(QtCore.Qt.AlignCenter)
        self.L_CP_Py.setObjectName("L_CP_Py")
        self.I_CP_Px = QtWidgets.QLabel(self.F_Current_Position)
        self.I_CP_Px.setGeometry(QtCore.QRect(210, 80, 100, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.I_CP_Px.setFont(font)
        self.I_CP_Px.setStyleSheet("QLabel{\n"
"    border-radius: 10px;\n"
"}")
        self.I_CP_Px.setAlignment(QtCore.Qt.AlignCenter)
        self.I_CP_Px.setObjectName("I_CP_Px")
        self.L_CP_Px = QtWidgets.QLabel(self.F_Current_Position)
        self.L_CP_Px.setGeometry(QtCore.QRect(210, 50, 100, 21))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.L_CP_Px.setFont(font)
        self.L_CP_Px.setStyleSheet("QLabel{\n"
"    border: none;\n"
"}")
        self.L_CP_Px.setAlignment(QtCore.Qt.AlignCenter)
        self.L_CP_Px.setObjectName("L_CP_Px")
        self.L_CP_Pz = QtWidgets.QLabel(self.F_Current_Position)
        self.L_CP_Pz.setGeometry(QtCore.QRect(210, 270, 100, 21))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.L_CP_Pz.setFont(font)
        self.L_CP_Pz.setStyleSheet("QLabel{\n"
"    border: none;\n"
"}")
        self.L_CP_Pz.setAlignment(QtCore.Qt.AlignCenter)
        self.L_CP_Pz.setObjectName("L_CP_Pz")
        self.B_Current_Position = QtWidgets.QPushButton(Current_Position)
        self.B_Current_Position.setGeometry(QtCore.QRect(1100, 130, 250, 31))
        font = QtGui.QFont()
        font.setFamily("Century")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.B_Current_Position.setFont(font)
        self.B_Current_Position.setStyleSheet("QPushButton{\n"
"    border: none;\n"
"    \n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.B_Current_Position.setObjectName("B_Current_Position")
        self.F_Limit_Switch_Magnet = QtWidgets.QFrame(Current_Position)
        self.F_Limit_Switch_Magnet.setGeometry(QtCore.QRect(1057, 550, 331, 101))
        self.F_Limit_Switch_Magnet.setStyleSheet("QFrame{\n"
"    border: 2px solid;\n"
"    border-radius: 20px;\n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.F_Limit_Switch_Magnet.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.F_Limit_Switch_Magnet.setFrameShadow(QtWidgets.QFrame.Raised)
        self.F_Limit_Switch_Magnet.setObjectName("F_Limit_Switch_Magnet")
        self.I_LS1 = QtWidgets.QLabel(self.F_Limit_Switch_Magnet)
        self.I_LS1.setGeometry(QtCore.QRect(20, 25, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.I_LS1.setFont(font)
        self.I_LS1.setStyleSheet("QLabel{\n"
"    border-radius: 25px;\n"
"}")
        self.I_LS1.setAlignment(QtCore.Qt.AlignCenter)
        self.I_LS1.setObjectName("I_LS1")
        self.I_LS2 = QtWidgets.QLabel(self.F_Limit_Switch_Magnet)
        self.I_LS2.setGeometry(QtCore.QRect(80, 25, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.I_LS2.setFont(font)
        self.I_LS2.setStyleSheet("QLabel{\n"
"    border-radius: 25px;\n"
"}")
        self.I_LS2.setAlignment(QtCore.Qt.AlignCenter)
        self.I_LS2.setObjectName("I_LS2")
        self.I_LS3 = QtWidgets.QLabel(self.F_Limit_Switch_Magnet)
        self.I_LS3.setGeometry(QtCore.QRect(140, 25, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.I_LS3.setFont(font)
        self.I_LS3.setStyleSheet("QLabel{\n"
"    border-radius: 25px;\n"
"}")
        self.I_LS3.setAlignment(QtCore.Qt.AlignCenter)
        self.I_LS3.setObjectName("I_LS3")
        self.I_LS4 = QtWidgets.QLabel(self.F_Limit_Switch_Magnet)
        self.I_LS4.setGeometry(QtCore.QRect(200, 25, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.I_LS4.setFont(font)
        self.I_LS4.setStyleSheet("QLabel{\n"
"    border-radius: 25px;\n"
"}")
        self.I_LS4.setAlignment(QtCore.Qt.AlignCenter)
        self.I_LS4.setObjectName("I_LS4")
        self.I_M = QtWidgets.QLabel(self.F_Limit_Switch_Magnet)
        self.I_M.setGeometry(QtCore.QRect(260, 25, 50, 50))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.I_M.setFont(font)
        self.I_M.setStyleSheet("QLabel{\n"
"    border-radius: 25px;\n"
"}")
        self.I_M.setAlignment(QtCore.Qt.AlignCenter)
        self.I_M.setObjectName("I_M")
        self.F_Current_Position.raise_()
        self.B_Current_Position.raise_()
        self.F_Limit_Switch_Magnet.raise_()
        self.B_Limit_Switch_Magnet.raise_()
        self.Set_Event()
        self.retranslateUi(Current_Position)
        QtCore.QMetaObject.connectSlotsByName(Current_Position)

    def retranslateUi(self, Current_Position):
        _translate = QtCore.QCoreApplication.translate
        self.B_Limit_Switch_Magnet.setText(_translate("Current_Position", "LIMIT SWITCH/MAGNET"))
        self.L_CP_Theta1.setText(_translate("Current_Position", "Theta1"))
        self.I_CP_Theta1.setText(_translate("Current_Position", ""))
        self.label_7.setText(_translate("Current_Position", "Theta2"))
        self.I_CP_Theta2.setText(_translate("Current_Position", ""))
        self.I_CP_Theta3.setText(_translate("Current_Position", ""))
        self.L_CP_Theta3.setText(_translate("Current_Position", "Theta3"))
        self.I_CP_Theta4.setText(_translate("Current_Position", ""))
        self.L_CP_Theta4.setText(_translate("Current_Position", "Theta4"))
        self.I_CP_Py.setText(_translate("Current_Position", ""))
        self.I_CP_Pz.setText(_translate("Current_Position", ""))
        self.L_CP_Py.setText(_translate("Current_Position", "Py"))
        self.I_CP_Px.setText(_translate("Current_Position", ""))
        self.L_CP_Px.setText(_translate("Current_Position", "Px"))
        self.L_CP_Pz.setText(_translate("Current_Position", "Pz"))
        self.B_Current_Position.setText(_translate("Current_Position", "CURRENT POSITION"))
        self.I_LS1.setText(_translate("Current_Position", "1"))
        self.I_LS2.setText(_translate("Current_Position", "2"))
        self.I_LS3.setText(_translate("Current_Position", "3"))
        self.I_LS4.setText(_translate("Current_Position", "4"))
        self.I_M.setText(_translate("Current_Position", "M"))

#=====================================================================================================
    def Set_Event(self):
        signal.Data_Current_Position.connect(self.Update_Position)
        signal.click_B_Drag_Drop.connect(self.Click_B_Drag_Drop)

    def Update_Position(self, data):
        self.I_CP_Theta1.setText(str(data[0]))
        self.I_CP_Theta2.setText(str(data[1]))
        self.I_CP_Theta3.setText(str(data[2]))
        self.I_CP_Theta4.setText(str(data[3]))
        self.I_CP_Px.setText(str(data[4]))
        self.I_CP_Py.setText(str(data[5]))
        self.I_CP_Pz.setText(str(data[6]))

        self.I_LS1.setStyleSheet(style_on if data[0] == 0 else style_off)
        self.I_LS2.setStyleSheet(style_on if data[1] == 0 else style_off)
        self.I_LS3.setStyleSheet(style_on if data[2] == 0 else style_off)
        self.I_LS4.setStyleSheet(style_on if data[3] == 0 else style_off)

    def Click_B_Drag_Drop(self,data):
        self.I_M.setStyleSheet(style_on if data else style_off)