function T = modifiedDH(alpha1,a1,d,theta)
    T=[cos(theta),-sin(theta),0,a1;...
    sin(theta)*cos(alpha1),cos(alpha1)*cos(theta),-sin(alpha1),-sin(alpha1)*d;...
    sin(theta)*sin(alpha1), cos(alpha1)*sin(alpha1), cos(alpha1),cos(alpha1)*d;...
    0,0,0,1];
end